### ISSUE TITLE
Website Renovierung Q2/2022

### ISSUE THREAD

**Issue by krother** [krother/academis_website#3]
### Ziel

Die Webseite www.academis.eu als Positionierungstool zu verbessern (für Kursmaterialien, wiederkehrende Kursteilnehmer und Kunden, neuen Content; eher nicht als direktes Verkaufswerkzeug)

### Aufgaben

- [x] Burger Menü zur Navigation sichtbar (irgendwo oben)
- [x] Navigation zurück ist möglich (von einem Artikel zu Themenseite z.b. `/teaching` oder von Themenseite zur Hauptseite `/`)
- [x] Neue Kategorie "Courses" im Menü
- [x] CSS optimieren, insbesondere vertikale Abstände
- [x] Banner oben mit dem runden Foto und tagline erstellen
- [x] Rest der Sidebar nach unten
- [x] Sidebar kann weg
- [x] responsive, so dass die Seite auf Mobile und PC gut aussieht
- [x] Schriftgröße kann gerne geändert werden
- [x] Die Testimonials werden dynamisch ausgewürfelt, kann weg falls das im Weg ist.

Fragen zu Details gerne als Kommentar in diesem Issue, falls sich ein größerer Dialog entwickelt, erstellen wir ein neues Issue

### Ressourcen

- [CSS, JavaScript und Bilder](https://github.com/krother/academis_website/tree/master/static)
- [HTML-Templates](https://github.com/krother/academis_website/tree/master/templates)

Die wichtigen Templates sind 

- `academis.html` (Hauptseite)
- `article_list.html` (Listenansicht für ein Thema)
- `article.html` (einzelner Post)

### Ablauf

Bitte nach Belieben eigene Branches erstellen und pushen.

**Comment by krother** [comment]
Burger Menü läuft bei mir und sieht toll aus :star_struck: :star_struck: :star_struck: . Ich überlege mir noch was im Menü in welcher Reihenfolge zu sehen sein soll. 

Habe die neueste Doku in den branch gemergt und das `.DS_Store` zu `.gitignore` hinzugefügt.

**Comment by LuiseBrandenburger** [comment]
Super, das freut mich 😀  . Ich werde heute auch den ganzen Tag mit der Seite verbringen, sobald ich fertig bin und Sehenswertes gepusht habe, gebe ich dir bescheid.

**Comment by LuiseBrandenburger** [comment]
Hi @krother ich habe zwei "kleine" Issues. 

1. ich habe ein kleines Problem beim mergen der Master Branch mit deinen Änderungen in meine Branch (ohne den merge darf ich nicht pushen). Da ich das mergen noch nicht so oft gemacht habe, habe ich gerade Angst, das ich etwas zerschieße.  
2. ich habe begonnen die Seitenstruktur anzupassen: die Sidebar in den Footer zu schieben, eine kleine Intro Section mit deinem Bild und dem About-Text anzulegen etc. Wenn ich das Projekt in Chrome im normalen Mode geöffnet habe, werden mir die Änderungen so angezeigt, wie ich sie mir vorstelle. Wenn ich Chrome allerdings im incognito-Mode öffne, werden meine Änderungen nur teilweise übernommen. Ich bin mir nun unsicher, welche Version die Korrekte ist.

Die aktuellen Styles sind noch nicht final. Ich arbeite mich immer von Außen nach Innen und erstelle erstmal die grobe Struktur und arbeite dann Schritt für Schritt an den Details. Nur FYI falls du es dir anguckst.

**Comment by krother** [comment]
Solange Du Deine Änderungen zuerst lokal committest, kann nichts kaputt gehen. Probier mal folgendes:

1. lokal git commit
2. git pull
3. wenn beim merge kein Konflikt angezeigt wird, merge bestätigen -> commit wird automatisch erzeugt
4. wenn ein Konflikt angezeigt wird, die konfliktierende Datei im Editor öffnen und bearbeiten (git zeigt recht deutlich an wo der Konflikt ist). anschließend git add + git commit
5. git push

Falls etwas nicht funktioniert können wir es auch zusammen durchgehen.

**Comment by krother** [comment]
Teil 2: Danke fürs update, weiß ich Bescheid. Keine Ahnung was das in Chrome ist. Wenn ich es mir anschaue sage ich Dir wie es im Firefox aussieht

**Comment by LuiseBrandenburger** [comment]
Ich habe hier mal einen Screenshot von meiner aktuellen Fehlermeldung eingefügt:
![Screen Shot 2022-04-27 at 16 25 03](https://user-images.githubusercontent.com/61413319/165541273-05164f25-509c-4ebc-b5f2-a0157049748a.png)

Sorry dafür, ich bin in Git noch nicht so ganz fit.

**Comment by LuiseBrandenburger** [comment]
Ich habe mir jetzt auch endlich mal Firefox runtergeladen. Dort sieht es gut aus bzw. so wie es aussehen sollte.

**Comment by krother** [comment]
> Sorry dafür, ich bin in Git noch nicht so ganz fit.

Nee das macht gar nichts. Das habe ich bei erfahrenen Programmierern auch schon erlebt. Und bei Spiced Absolventen plane ich es fest ein :-)

Also ein `git pull` sollte da helfen.

**Comment by LuiseBrandenburger** [comment]
hm ich glaube das Problem liegt darin, dass ich zuerst etwas gepushed habe, bevor ich deine Änderungen von gestern gemerged habe. Ich konnte den git pull durchführen aber ich kann leider immer noch nicht pushen. Ich gucke morgen wie ich es lösen kann (ich habe leider jetzt einen Termin).
![Screen Shot 2022-04-27 at 16 51 50](https://user-images.githubusercontent.com/61413319/165546946-a32482e5-258a-4063-bf60-2b59251e7521.png)

Immerhin weiß ich jetzt wie ich das css aus dem cache löschen kann. D.h. das Problem mit dem Anzeigen des Stylings ist gelöst.

**Comment by krother** [comment]
kann mich morgen auch dazuschalten um beim unblocken zu helfen.

**Comment by LuiseBrandenburger** [comment]
ja, eventuell würde ich dafür auf dich zukommen.

**Comment by LuiseBrandenburger** [comment]
Hallo Kristian,
ich hatte heute Vormittag, vor meinem Zahnarzttermin, nochmal versucht das Git Problem zu lösen. Leider bin ich nicht weit gekommen. Falls du morgen irgendwann im Laufe des Tages nochmal 10min für mich hättest um kurz den Fehler zu finden, würde ich mich sehr freuen. Zeitlich kann ich mich auch ganz nach dir richten.

**Comment by krother** [comment]
Hier ist aus meiner Sicht alles erledigt. Schließe das Ticket. :star: :star: :star:
