### ISSUE TITLE
Website Renovierung Leftovers

### ISSUE THREAD

**Issue by krother** [krother/academis_website#6]
merge oder ändern:

@krother

- [x] toc in footer umbenennen
- [x] footer links mergen
- [x] copyright unterste Zeile + Link zu Luises LinkedIn
- [x] 3 Bilder für Courses - moved to #7 
- [x] Tabellen in Challenge-Listen - moved to #5 
- [x] burger menu: typo + restliche Links

@LuiseBrandenburger 
- [x] responsive design für head größere Screens Hauptseite oben
- [x] courses als Absatz unter header
- [x] kleine Anpassungen an vertikalen Abständen

**Comment by krother** [comment]
Habe den Footer etwas im branch `dev` editiert. Bin soweit zufrieden. Zwei Kleinigkeiten sind dort noch übrig: das Telefon soll grün sein und Deine URL fehlt. 

Kann gerne beim Merge behilflich sein, aber nicht vor Donnerstag ;-)

**Comment by LuiseBrandenburger** [comment]
Hej hej Kristian, alles klar :). Wenn ich morgen Probleme haben sollte, gebe ich dir bescheid. Lieben Dank!

**Comment by LuiseBrandenburger** [comment]
![Screen Shot 2022-05-06 at 11 09 56](https://user-images.githubusercontent.com/61413319/167102853-036822c3-1bf4-4a6a-a09e-b16b50379c69.png)
Hello Kristian. Ich bin soweit fertig mit allen Anpassungen. Es gibt noch einen kleinen Bug beim rendern deines Profilbildes auf den Unterseiten. Ansonsten funktioniert alles und die Seiten sind alle schön responsive 😀. Ich habe den Bereich für die Courses mit Platzhaltern angelegt und den Footer noch einmal ein klein wenig überarbeitet. Gib mir sehr gerne Feedback falls ich noch etwas anpassen kann. Sobald du die Infos zusammen hast, kann ich dann noch die Links in der Navbar anpassen.

**Comment by krother** [comment]
@LuiseBrandenburger Das Bild sehe ich übrigens nicht, das "broken Link" Symbol aber auch nicht. Ist ok wie es ist.

**Comment by krother** [comment]
Ich mache das Issue erst einmal zu.
